export const products=[
    {
        name:"产品折扣",//字段名称String
        en:'cpzk',
        type:"string",//String
        desc:{
            name:"产品折扣",
            min:0,
            max:12,
            isReq:true,//是否必输
            isEnabled:true,//是否可用
            isShow:true,//是否显示
            defalut:"啦啦默认值",//默认值
        }//Object
    }
];
export const string={
    name:"产品折扣",//String
    min:0,//最小长度Number
    max:12,//最大长度Number
    isReq:true,//是否必输Boolean
    isEnabled:true,//是否可用Boolean
    isShow:true,//是否显示Boolean
    defalut:"",//默认值String
};
export const dateString={
    name:"产品折扣",//String
    min:"2020/09/12 00/00/00",//最小长度String
    max:"2021/09/12 00/00/00",//最大长度String
    isReq:true,//是否必输Boolean
    isEnabled:true,//是否可用Boolean
    isShow:true,//是否显示Boolean
    defalut:"",//默认值String
};
export const number={
    name:"产品折扣",//String
    min:[
        0,//最小值Number
        false,//不包含0，true包含，false不包含Boolean
    ],
    max:[
        100,//最大值
        true,//包含100，true包含，false不包含Boolean
    ],
    floatLength:3,//保留几位小数
    isReq:true,//是否必输Boolean
    isEnabled:true,//是否可用Boolean
    isShow:true,//是否显示Boolean
    defalut:"",//默认值String
};
export const radio={
    isReq:true,//是否必输Boolean
    isEnabled:true,//是否可用Boolean
    isShow:true,//是否显示Boolean
    defalut:"Y",//默认值String
    values:[
                {
                    name:'是',//String
                    value:'Y',//String
                    with:['aa','bb','cc','dd'],//所有关联字段
                    wTrue:['aa','bb'],//放开置灰
                    withFalse:['cc','dd']//设置为置灰
                },//
                {
                    name:'否',//String
                    value:'N',//String
                    with:['aa','bb','cc','dd'],//所有关联字段
                    withTrue:['cc','dd'],//放开置灰
                    withFalse:['aa','bb']//设置为置灰
                }
            ]//Array
};
export const checkbox={
    isReq:true,//是否必输Boolean
    isEnabled:true,//是否可用Boolean
    isShow:true,//是否显示Boolean
    defalut:[],//默认值
    values:[
        {
            name:'是',//String
            value:'Y',//String
            with:['aa','bb','cc','dd'],//所有关联字段
            withTrue:['aa','bb'],//放开置灰
            withFalse:['cc','dd']//设置为置灰
        },
        {
            name:'否',//String
            value:'N',//String
            with:['aa','bb','cc','dd'],//所有关联字段
            withTrue:['cc','dd'],//放开置灰
            withFalse:['aa','bb']//设置为置灰
        }
    ]
};